spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/

server:
  port: 8090
  servlet:
    context-path: /fifamatch
    session:
      timeout: 1800

logging:
  level:
    root: DEBUG

app:
  api:
    key: api-key
    url: api-url
